.gitignore
build.gradle
src/main/java/com/shallwe/domain/auth/application/AuthService.java
src/main/java/com/shallwe/domain/auth/domain/Token.java
src/main/java/com/shallwe/domain/user/application/UserService.java
src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
src/main/java/com/shallwe/domain/user/dto/UserDeleteRes.java
src/main/java/com/shallwe/domain/user/dto/UserRes.java
src/main/java/com/shallwe/domain/user/exception/DefaultException.java
src/main/java/com/shallwe/domain/user/exception/DefaultNullPointerException.java
src/main/java/com/shallwe/domain/user/exception/InvalidParameterException.java
src/main/java/com/shallwe/domain/user/exception/TokenExpirationException.java
src/main/java/com/shallwe/domain/user/presentation/UserController.java
src/main/java/com/shallwe/domain/user/presentation/UserExceptionController.java
src/main/java/com/shallwe/global/DefaultAssert.java
src/main/java/com/shallwe/global/controller/ExceptionController.java
src/main/java/com/shallwe/global/dto/response/ResponseCustom.java
src/main/java/com/shallwe/global/error/ApiControllerAdvice.java
src/main/java/com/shallwe/global/error/DefaultException.java
src/main/java/com/shallwe/global/error/DefaultNullPointerException.java
src/main/java/com/shallwe/global/error/InvalidParameterException.java

#14 setting and refactoring : 프로젝트 초기설정 리펙토링

---

src/main/java/com/shallwe/ShallWeApplication.java

#14 프로젝트 리펙토링 코드 수정

---

Dockerfile

#19 도커 파일 수정

---

.gitignore
src/main/java/com/shallwe/global/config/JasyptConfig.java
src/main/resources/oauth2/application-oauth2.yml

#27 oauth2 암호화

---

Dockerfile

#19 dockerfile entrypoint수정

---

Dockerfile
src/main/java/com/shallwe/ShallWeApplication.java

#19 도커파일 수정2

---

build.gradle
src/main/java/com/shallwe/domain/test/testController.java
src/main/resources/application.properties

#38 cicd test

---

src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
src/main/java/com/shallwe/domain/reservation/dto/DeleteReservationRes.java
src/main/java/com/shallwe/domain/reservation/dto/ReservationRequest.java
src/main/java/com/shallwe/domain/reservation/dto/ReservationResponse.java
src/main/java/com/shallwe/domain/reservation/dto/UpdateReservationReq.java
src/main/java/com/shallwe/domain/reservation/exception/InvalidUserException.java
src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java

1. 예약 기능 구현 (조회, 추가, 수정, 삭제) 
2. 엔티티의 기존 DateTime Date -> LocalDateTime Date 로 수정( Figma에 시간도 정할 수 있는 것 같아 수정했습니다.)
3. 서비스에 들어있는 set구문 dto에서 처리하도록 리팩토링 
#전체 예약 조회
#유저id로 예약 조회
#예약 등록
#예약 수정
#예약 삭제
Closes #36

[feat] 예약 기능을 구현한다.

---

build.gradle
src/main/generated/com/shallwe/domain/auth/domain/QToken.java
src/main/generated/com/shallwe/domain/common/QBaseEntity.java
src/main/generated/com/shallwe/domain/experience_gift/domain/QExpCategory.java
src/main/generated/com/shallwe/domain/experience_gift/domain/QExperienceGift.java
src/main/generated/com/shallwe/domain/experience_gift/domain/QSttCategory.java
src/main/generated/com/shallwe/domain/experience_gift/domain/QSubtitle.java
src/main/generated/com/shallwe/domain/reservation/domain/QReservation.java
src/main/generated/com/shallwe/domain/user/domain/QUser.java
src/main/java/com/shallwe/domain/experience_gift/application/ExperienceGiftService.java
src/main/java/com/shallwe/domain/experience_gift/application/ExperienceGiftServiceImpl.java
src/main/java/com/shallwe/domain/experience_gift/domain/ExperienceGift.java
src/main/java/com/shallwe/domain/experience_gift/dto/ExperienceDetailRes.java
src/main/java/com/shallwe/domain/experience_gift/dto/ExperienceRes.java
src/main/java/com/shallwe/domain/experience_gift/exception/ExperienceGiftNotFoundException.java
src/main/java/com/shallwe/domain/experience_gift/presentation/ExperienceGiftController.java
src/main/java/com/shallwe/domain/experience_gift/repository/ExperienceGiftRepository.java
src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
src/main/java/com/shallwe/global/config/querydsl/QueryDslConfig.java

#41 경험검색조회, 경험상세조회 기능구현,querydsl설정 추가

---

src/main/generated/com/shallwe/domain/reservation/domain/QReservation.java
src/main/java/com/shallwe/domain/experience_gift/application/ExperienceGiftService.java
src/main/java/com/shallwe/domain/experience_gift/application/ExperienceGiftServiceImpl.java
src/main/java/com/shallwe/domain/experience_gift/domain/ExperienceGift.java
src/main/java/com/shallwe/domain/experience_gift/domain/ExperienceGiftStatus.java
src/main/java/com/shallwe/domain/experience_gift/dto/response/ExperienceDetailRes.java
src/main/java/com/shallwe/domain/experience_gift/dto/response/ExperienceExpCategoryRes.java
src/main/java/com/shallwe/domain/experience_gift/dto/response/ExperienceRes.java
src/main/java/com/shallwe/domain/experience_gift/dto/response/ExperienceSttCategoryRes.java
src/main/java/com/shallwe/domain/experience_gift/presentation/ExperienceGiftController.java
src/main/java/com/shallwe/domain/experience_gift/repository/ExperienceGiftQuerydslRepository.java
src/main/java/com/shallwe/domain/experience_gift/repository/ExperienceGiftQuerydslRepositoryImpl.java
src/main/java/com/shallwe/domain/experience_gift/repository/ExperienceGiftRepository.java
src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
src/main/java/com/shallwe/domain/reservation/dto/ReservationRequest.java
src/main/java/com/shallwe/domain/reservation/dto/ReservationResponse.java

#41 상황별 카테고리별 경험 조회, 상황별 추천 경험 조회 기능구현

---

src/main/java/com/shallwe/domain/memory_photo/application/MemoryPhotoService.java
src/main/java/com/shallwe/domain/memory_photo/application/MemoryPhotoServiceImpl.java
src/main/java/com/shallwe/domain/memory_photo/domain/MemoryPhoto.java
src/main/java/com/shallwe/domain/memory_photo/dto/MemoryPhotoDetailRes.java
src/main/java/com/shallwe/domain/memory_photo/presentation/MemoryPhotoController.java
src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java

- [] 💯 테스트는 잘 통과했나요?
우선 Memory_Photo 도메인 셋팅 완료했고 Entity도 생성해놨습니다. 현욱님 receiver 수정되는 대로 API 작업 들어가겠습니다!
Closes #33

[feat]: Memory_Photo 도메인 구현

---

src/main/generated/com/shallwe/domain/memory_photo/domain/QMemoryPhoto.java
src/main/resources/database/application-database.yml

#25 db암호화 변경

---

src/main/resources/oauth2/application-oauth2.yml

oauth2 리다이렉트 uri 암호화 변경

---

src/main/generated/com/shallwe/domain/memory_photo/domain/QMemoryPhoto.java
src/main/java/com/shallwe/domain/experience_gift/application/ExperienceGiftService.java
src/main/java/com/shallwe/domain/experience_gift/application/ExperienceGiftServiceImpl.java
src/main/java/com/shallwe/domain/experience_gift/dto/response/ExperienceExpCategoryRes.java
src/main/java/com/shallwe/domain/experience_gift/dto/response/ExperienceRes.java
src/main/java/com/shallwe/domain/experience_gift/dto/response/ExperienceSttCategoryRes.java
src/main/java/com/shallwe/domain/experience_gift/presentation/ExperienceGiftController.java
src/main/java/com/shallwe/domain/experience_gift/repository/ExperienceGiftQuerydslRepository.java
src/main/java/com/shallwe/domain/experience_gift/repository/ExperienceGiftQuerydslRepositoryImpl.java
src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
src/main/java/com/shallwe/global/config/Constant.java

#41 상황별 경혐별 카테고리 가격 높은순 낮은순 정렬기능

---

src/main/generated/com/shallwe/domain/memory_photo/domain/QMemoryPhoto.java
src/main/generated/com/shallwe/domain/reservation/domain/QReservation.java
src/main/generated/com/shallwe/domain/user/domain/QUser.java
src/main/java/com/shallwe/domain/memory_photo/application/MemoryPhotoService.java
src/main/java/com/shallwe/domain/memory_photo/application/MemoryPhotoServiceImpl.java
src/main/java/com/shallwe/domain/memory_photo/domain/MemoryPhoto.java
src/main/java/com/shallwe/domain/memory_photo/domain/repository/MemoryPhotoRepository.java
src/main/java/com/shallwe/domain/memory_photo/dto/MemoryPhotoDetailRes.java
src/main/java/com/shallwe/domain/memory_photo/presentation/MemoryPhotoController.java
src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
src/main/java/com/shallwe/domain/reservation/dto/ReservationRequest.java
src/main/java/com/shallwe/domain/reservation/dto/ReservationResponse.java
src/main/java/com/shallwe/domain/user/domain/User.java

Memory Photo 조회 API 구현
Closes #55

[FEAT]: Memory Photo 조회 API

---

src/main/java/com/shallwe/domain/experience_gift/application/ExperienceGiftService.java
src/main/java/com/shallwe/domain/experience_gift/application/ExperienceGiftServiceImpl.java
src/main/java/com/shallwe/domain/experience_gift/domain/ExperienceGift.java
src/main/java/com/shallwe/domain/experience_gift/dto/request/ExperienceReq.java
src/main/java/com/shallwe/domain/experience_gift/dto/response/ExperienceDetailRes.java
src/main/java/com/shallwe/domain/experience_gift/exception/ExpCategoryNotFoundException.java
src/main/java/com/shallwe/domain/experience_gift/exception/SttCategoryNotFoundException.java
src/main/java/com/shallwe/domain/experience_gift/exception/SubtitleNotFoundException.java
src/main/java/com/shallwe/domain/experience_gift/presentation/ExperienceGiftController.java
src/main/java/com/shallwe/domain/experience_gift/repository/ExpCategoryRepository.java
src/main/java/com/shallwe/domain/experience_gift/repository/SttCategoryRepository.java
src/main/java/com/shallwe/domain/experience_gift/repository/SubtitleRepository.java

경험 선물 생성 기능 개발
Service, Controller, Repository, Exception 추가하였습니다. 
Closes #61

[Feat] 경험 선물 생성을 개발한다.

---

src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoService.java
src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoServiceImpl.java
src/main/java/com/shallwe/domain/memoryphoto/dto/MemoryPhotoDetailRes.java
src/main/java/com/shallwe/domain/memoryphoto/presentation/MemoryPhotoController.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java

- MemoryPhoto API Response 수정
- API 요청 쿼리 파라미터 date 형식 [YYYY-MM-DD] 로 변경(final)
Closes #123

refactor: MemoryPhoto API Response 수정 및 요청 파라미터 date 형식 변경

---

.github/workflows/github-actions.yml

fix:github-actions.yml수정

---

src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGiftStatus.java

feat:경험선물 엔티티 연관관계 추가

---

src/main/java/com/shallwe/domain/shopowner/domain/ShopOwner.java

ShopOwner 엔티티 수정사항 반영
Closes #134

[chore] ShopOwner 엔티티 수정사항 반영

---

src/main/java/com/shallwe/domain/auth/application/AuthService.java
src/main/java/com/shallwe/domain/auth/application/CustomUserDetailsService.java
src/main/java/com/shallwe/domain/auth/dto/ShopOwnerSignInReq.java
src/main/java/com/shallwe/domain/auth/dto/ShopOwnerSignUpReq.java
src/main/java/com/shallwe/domain/auth/exception/InvalidPasswordException.java
src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
src/main/java/com/shallwe/domain/shopowner/domain/repository/ShopOwnerRepository.java
src/main/java/com/shallwe/domain/shopowner/dto/ShopOwnerChangePasswordReq.java
src/main/java/com/shallwe/domain/shopowner/exception/AlreadyExistPhoneNumberException.java
src/main/java/com/shallwe/domain/shopowner/exception/InvalidPhoneNumberException.java
src/main/java/com/shallwe/domain/shopowner/exception/InvalidShopOwnerException.java
src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java
src/main/java/com/shallwe/global/config/security/token/UserPrincipal.java

#137 
- 사장 회원가입
- 사장 로그인
- 사장 비밀번호 변경(AccessToken 필요)
구현한 것부터 먼저 올립니당

[feat] 사장 회원가입, 로그인, 비밀번호 변경 API 구현 

---

src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftRepository.java
src/main/java/com/shallwe/domain/experiencegift/dto/response/AdminExperienceRes.java
src/main/java/com/shallwe/domain/experiencegift/presentation/AdminExperienceGiftController.java

[Feat] 관리자 상품 목록 조회 API구현

---

src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
src/main/java/com/shallwe/domain/experiencegift/dto/response/AdminMainRes.java
src/main/java/com/shallwe/domain/experiencegift/presentation/AdminExperienceGiftController.java
src/main/java/com/shallwe/domain/reservation/domain/ReservationStatus.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java

ReservationStatus클래스 변경사항 있습니다. 참고해주세요 @hyunw9 
Closes #139

[Feat] 관리자 메인 페이지 API구현

---

src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java

[Fix] ShopOwner URL 주소를 수정한다. 

---

src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoServiceImpl.java
src/main/java/com/shallwe/domain/memoryphoto/dto/MemoryPhotoDetailRes.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java

Reservation Entitiy 스펙 변경으로 인한 Type 오류 해결
Closes #152

[FIX] Reservation Entitiy 스펙 변경으로 인한 Type 오류 해결

---

src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
src/main/java/com/shallwe/domain/reservation/dto/ReservationRequest.java
src/main/java/com/shallwe/domain/reservation/dto/ReservationUserReq.java
src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java

사용자 예약 추가 로직
request의 시간 날짜로 예약 검색 -> 예약 가능 상태이면 예약 정보 업데이트 후 상태를 변경한다. 
Closes #154

사용자 예약 추가 로직을 개발한다.

---

src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/dto/ReservationUserReq.java
src/main/java/com/shallwe/domain/reservation/dto/UpdateReservationReq.java
src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java

사장님 예약 등록 구분자 추가 
유저 예약 등록 dto 수정

예약 등록시 url, dto를 수정한다. 

---

src/main/java/com/shallwe/domain/auth/application/AuthService.java
src/main/java/com/shallwe/domain/user/application/UserService.java
src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
src/main/java/com/shallwe/domain/user/presentation/UserController.java

- /api/v1/users/inactive 로 URL 변경
- Soft delete 방식으로 변경

[FIX] User 회원 탈퇴 로직 변경

---

src/main/java/com/shallwe/domain/reservation/domain/Reservation.java

reservation entity를 수정한다.

---

src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepository.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepositoryImpl.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
src/main/java/com/shallwe/domain/user/dto/ReceiveGiftDetailRes.java
src/main/java/com/shallwe/domain/user/dto/SendGiftDetailRes.java
src/main/java/com/shallwe/domain/user/dto/UserDetailRes.java

- 삭제 된 유저 조회 시 NullPointException 현상 해결
Closes #163

[FIX] 삭제 된 유저 조회 시 NullPointException 현상 해결

---

src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
src/main/java/com/shallwe/domain/reservation/domain/ReservationStatus.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
src/main/java/com/shallwe/domain/reservation/dto/ReservationResponse.java
src/main/java/com/shallwe/domain/reservation/dto/ValidTimeSlotRes.java
src/main/java/com/shallwe/domain/reservation/exception/InvalidAvailableTimeException.java
src/main/java/com/shallwe/domain/reservation/exception/InvalidUserException.java
src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java

예약 확정, 조회, 가능 시간대 조회 기능을 개발한다.

---

src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftQuerydslRepositoryImpl.java
src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftRepository.java
src/main/java/com/shallwe/domain/experiencegift/dto/request/AdminExperienceReq.java
src/main/java/com/shallwe/domain/experiencegift/presentation/AdminExperienceGiftController.java

관리자 경험 선물 수정, 삭제 api 기능구현
선물 삭제는 소프트 delete를 이용하여 삭제 -> stauts상태가 ACTIVE에서 DELETE
추가로 선물 조회 로직도 status상태가 ACTIVE일때만 조회되도록 수정
Closes #138

[Feat] 관리자 경험 선물 수정, 삭제 api 기능구현

---

src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftImgRepository.java
src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExplanationRepository.java

[Hotfix] 충돌 해결, 관리자 상품 수정 api수정

---

src/main/java/com/shallwe/domain/user/application/UserService.java
src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
src/main/java/com/shallwe/domain/user/domain/Complain.java
src/main/java/com/shallwe/domain/user/domain/repository/ComplainRepository.java
src/main/java/com/shallwe/domain/user/dto/PostComplainReq.java
src/main/java/com/shallwe/domain/user/presentation/UserController.java

- 회원 탈퇴 시 불편사항도 같이 등록하도록 수정
Closes #166

[FEAT] 회원 탈퇴 시 불편사항도 같이 등록하도록 수정

---

src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
src/main/java/com/shallwe/domain/experiencegift/dto/request/AdminExperienceReq.java

[Fix] 선물 등록 유의사항 컬럼 등록

---

src/main/java/com/shallwe/domain/experiencegift/dto/request/AdminExperienceReq.java
src/main/java/com/shallwe/domain/experiencegift/dto/request/ExplanationReq.java

[Fix] 관리자 경험 선물 등록 reqeust 타입 수정, url->key로 수정

---

src/main/java/com/shallwe/domain/experiencegift/domain/Explanation.java

[Chore]  toDto클래스도 url->key로 변경

---

src/main/java/com/shallwe/domain/reservation/domain/Reservation.java

Reservation Entity NotNull 제거 

Reservation Entity NotNull 어노테이션 삭제 

---

src/main/java/com/shallwe/domain/reservation/application/ReservationService.java
src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
src/main/java/com/shallwe/domain/reservation/domain/ReservationStatus.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
src/main/java/com/shallwe/domain/shopowner/domain/repository/ShopOwnerRepository.java
src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java

상품ID, 날짜로 예약을 조회한다. 

---

src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
src/main/java/com/shallwe/domain/shopowner/domain/ShopOwner.java
src/main/java/com/shallwe/domain/shopowner/dto/ShopOwnerIdentificationReq.java
src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java

사장 신분증/사업자등록증/통장사본 등록 API 구현
키를 올리면 내부적으로 이미지URL로 변환해서 저장
Closes #184

feat: 사장 신분증/사업자등록증/통장사본 등록 API 구현

---

src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java

빌드 충돌 오류를 해결한다. 

---

src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoService.java
src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoServiceImpl.java
src/main/java/com/shallwe/domain/memoryphoto/domain/MemoryPhoto.java
src/main/java/com/shallwe/domain/memoryphoto/domain/repository/MemoryPhotoRepository.java
src/main/java/com/shallwe/domain/memoryphoto/dto/MemoryPhotoDetailRes.java
src/main/java/com/shallwe/domain/memoryphoto/dto/MemoryPhotoUserDetailRes.java
src/main/java/com/shallwe/domain/memoryphoto/exception/MemoryPhotoUploaderMismatchException.java
src/main/java/com/shallwe/domain/memoryphoto/presentation/MemoryPhotoController.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepository.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepositoryImpl.java

- MemoryPhoto 삭제 API 구현
- MemoryPhoto 조회 시 Uploader 판별 Response 추가
Closes #188

feat: MemoryPhoto 삭제 API 구현

---

src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoServiceImpl.java
src/main/java/com/shallwe/domain/memoryphoto/domain/repository/MemoryPhotoRepository.java
src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepository.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepositoryImpl.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
src/main/java/com/shallwe/domain/shopowner/domain/repository/ShopOwnerRepository.java
src/main/java/com/shallwe/domain/user/application/UserService.java
src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
src/main/java/com/shallwe/domain/user/domain/repository/UserRepository.java
src/main/java/com/shallwe/domain/user/dto/ReceiveGiftDetailRes.java
src/main/java/com/shallwe/domain/user/exception/InvalidPhoneNumberException.java
src/main/java/com/shallwe/domain/user/exception/InvalidUserException.java
src/main/java/com/shallwe/domain/user/presentation/UserController.java

- ReservationRepository 안 쓰는 코드가 너무 많아서 정리 한번 했슴다
- 코드 컨벤션대로 고칠만한거 보이는 건 다 고쳤습니다
Closes #193

refactor: 안 쓰는 코드 정리 + 코드 컨벤션대로 수정

---

src/main/java/com/shallwe/domain/user/dto/ReceiveGiftDetailRes.java

- 받은 유저 선물 조회 API experienceGiftId Response 추가
Closes #195

fix: 받은 유저 선물 조회 API experienceGiftId Response 추가

---

src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceDetailRes.java
src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceSttCategoryRes.java

#201 refactor:필요없는 res 컬럼 삭제

---

src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepositoryImpl.java

QueryDsl , 메서드 명 관련 충돌 해결 
Closes #200

병합 충돌을 해결한다. 

---

src/main/java/com/shallwe/domain/reservation/domain/Reservation.java

컬럼명을 수정한다. 

---

src/main/java/com/shallwe/domain/reservation/domain/Reservation.java

컬럼명을 수정한다.

---

.github/workflows/github-actions.yml

feat 인프라 구축

---

src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftRepository.java
src/main/java/com/shallwe/domain/experiencegift/dto/response/ShopOwnerExperienceDetailsRes.java
src/main/java/com/shallwe/domain/experiencegift/presentation/ShopOwnerExperienceGiftController.java

feat:사장님 앱 경험 선물 상세 조회 API

---

src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/dto/request/OwnerReservationCreate.java

- [] 🏗️ 빌드는 성공했나요?
Closes #219

사장님 예약 추가시 ownerID 제거한다.

---

build.gradle
src/main/java/com/shallwe/global/config/security/SecurityConfig.java

- Springboot 3.1.1 -> 3.2.2 버전 업
- FowardedHeaderFilter Bean 등록

[DEPENDENCY] FowardedHeaderFilter를 위한 Spring 3.2.2 버전 업

---

.github/workflows/dev-cicd.yml
.github/workflows/prod-cicd.yml
.gitignore

- prod deploy script 작성
- dev deploy sciprt 수정

infra: prod deploy script 작성

---

.github/workflows/dev-cicd.yml
.github/workflows/prod-cicd.yml
src/main/java/com/shallwe/ShallWeApplication.java

chore: deploy script 수정

---

src/main/java/com/shallwe/global/config/WebConfig.java

 infra: cors설정

---

src/main/java/com/shallwe/global/config/WebConfig.java

fix: cors수정

---

src/main/java/com/shallwe/global/config/WebConfig.java

fix: core 설정 변경

---

.github/workflows/dev-cicd.yml
.github/workflows/prod-cicd.yml

main <- develop

---

src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java

사장 예약 추가시 조회 레포지토리를 변경한다.

---

src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
src/main/java/com/shallwe/global/config/WebConfig.java

배포 서버 <- 개발 서버  병합 

---

build.gradle

로컬에서 정상적으로 메트릭 수집 , prometheus GUI 실행 확인했습니다. 머지해주시면 dev 서버에 우선적으로 적용해보겠습니다~

모니터링 종속성을 추가한다. 

---

src/main/java/com/shallwe/global/config/security/SecurityConfig.java

지금 prometheus url 접근이 Spring Security 에 막혀서 접근이 안되는 관계로 (401) 
시큐리티 권한 해제해 놓겠습니다. 
그라파나 자체 로그인 사용하면 될듯 하네요 

모니터링 관련 시큐리티 설정을 변경한다.

---

.github/workflows/dev-cicd.yml
src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
src/main/java/com/shallwe/global/config/security/SecurityConfig.java

```
ssh dev sudo docker rm -f $(ssh dev sudo docker ps -qa) Shallwe-Application
ssh dev sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
ssh dev sudo docker run -dp 80:8080 --name Shallwe-Application ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
```

CD시 Shallwe-Application 만 변경하도록 수정한다. 

---

src/main/java/com/shallwe/domain/experiencegift/dto/response/ExplanationRes.java

hotfix: Explation img response AwsS3Util 제거

---

.github/workflows/dev-cicd.yml
.github/workflows/prod-cicd.yml
src/main/java/com/shallwe/ShallWeApplication.java
src/main/java/com/shallwe/domain/experiencegift/dto/response/ExplanationRes.java

- explationres todto 메소드 AwsS3Util 삭제

hotfix: explationres todto 메소드 AwsS3Util 삭제

---

src/main/java/com/shallwe/domain/experiencegift/dto/response/ExplanationRes.java
src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java

- Reservation 조회할 때 ExperienceGift Id 안넣어서 여러 개 조회되는 현상 수정

hotfix: Reservation 등록 API 오류 수정

---

src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java

* fix: Explation img response AwsS3Util 제거
* hotfix: Reservation 등록 API ExperienceGift 파라미터 추가

hotfix: Reservation 등록 API 오류 수정 (#250)

---

src/main/java/com/shallwe/domain/experiencegift/dto/response/ExplanationRes.java
src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepository.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepositoryImpl.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
src/main/java/com/shallwe/domain/user/domain/User.java
src/main/java/com/shallwe/domain/user/dto/ReceiveGiftDetailRes.java
src/main/java/com/shallwe/domain/user/dto/SendGiftDetailRes.java
src/main/java/com/shallwe/domain/user/dto/UserDetailRes.java

- User Entity @Where 어노테이션 제거
- UserDetailRes Status 컬럼 추가
- 보낸 선물 Response ExperienceGiftId 컬럼 추가

fix: 받은 선물 탈퇴한 회원 조회 안되는 현상 수정

---

src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepository.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepositoryImpl.java
src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
src/main/java/com/shallwe/domain/user/domain/User.java
src/main/java/com/shallwe/domain/user/dto/ReceiveGiftDetailRes.java
src/main/java/com/shallwe/domain/user/dto/SendGiftDetailRes.java
src/main/java/com/shallwe/domain/user/dto/UserDetailRes.java

* fix: Explation img response AwsS3Util 제거
* hotfix: Reservation 등록 API ExperienceGift 파라미터 추가
* fix: User Entity @Where 어노테이션 제거
* fix: 받은 선물 조회 탈퇴한 유저 조회 안되는 현상 수정

hotfix: 받은 선물 탈퇴한 회원 조회 안되는 현상 수정 (#252)

---

src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceDetailRes.java
src/main/java/com/shallwe/domain/user/domain/User.java

chore: 경험 선물 상세 API note 컬럼 추가

---

src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceDetailRes.java
src/main/java/com/shallwe/domain/user/domain/User.java

chore: 경험 선물 상세 API note 컬럼 추가 (#257)

---

src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java

ID 반환시 NPE를 해결한다 

---

src/main/java/com/shallwe/domain/shopowner/domain/ShopOwner.java

- shopOwner reservationList 어노테이션 수정
Closes #262

fix: shopOwner reservationList 어노테이션 수정

---

src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGiftExperienceCategory.java
src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGiftSituationCategory.java
src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftQuerydslRepository.java
src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftQuerydslRepositoryImpl.java
src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceDetailRes.java
src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceGiftRes.java
src/main/java/com/shallwe/domain/experiencegift/presentation/ExperienceGiftV2Controller.java
src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationService.java
src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
src/main/java/com/shallwe/domain/user/domain/User.java
src/main/java/com/shallwe/global/config/Constant.java

- 경험 상품 조회 페이징(무한 스크롤) API 구현
#256

feat: 경험 상품 조회 페이징 API 구현

---

build.gradle
src/main/java/com/shallwe/domain/auth/application/AuthService.java
src/main/java/com/shallwe/domain/auth/application/CustomTokenProviderService.java
src/main/java/com/shallwe/domain/auth/dto/AppleSignInReq.java
src/main/java/com/shallwe/domain/auth/dto/AppleSignInRes.java
src/main/java/com/shallwe/domain/auth/dto/SignUpReq.java
src/main/java/com/shallwe/domain/auth/exception/UnRegisteredUserException.java
src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
src/main/java/com/shallwe/domain/user/domain/Provider.java
src/main/java/com/shallwe/global/config/FeignConfig.java
src/main/java/com/shallwe/global/config/feign/FeignConfig.java
src/main/java/com/shallwe/global/config/security/auth/OAuth2UserInfoFactory.java
src/main/java/com/shallwe/global/config/security/auth/company/Kakao.java
src/main/java/com/shallwe/global/infrastructure/feign/apple/AppleClient.java
src/main/java/com/shallwe/global/infrastructure/feign/apple/dto/ApplePublicKeyRes.java
src/main/java/com/shallwe/global/utils/AppleJwtUtils.java

feat: 애플 로그인 API 구현

---

build.gradle
src/main/java/com/shallwe/domain/auth/application/AuthService.java
src/main/java/com/shallwe/domain/auth/application/CustomTokenProviderService.java
src/main/java/com/shallwe/domain/auth/dto/AppleSignInReq.java
src/main/java/com/shallwe/domain/auth/dto/AppleSignInRes.java
src/main/java/com/shallwe/domain/auth/dto/SignUpReq.java
src/main/java/com/shallwe/domain/auth/exception/UnRegisteredUserException.java
src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
src/main/java/com/shallwe/domain/user/domain/Provider.java
src/main/java/com/shallwe/global/config/FeignConfig.java
src/main/java/com/shallwe/global/config/security/auth/OAuth2UserInfoFactory.java
src/main/java/com/shallwe/global/config/security/auth/company/Kakao.java
src/main/java/com/shallwe/global/infrastructure/feign/apple/AppleClient.java
src/main/java/com/shallwe/global/infrastructure/feign/apple/dto/ApplePublicKeyRes.java
src/main/java/com/shallwe/global/utils/AppleJwtUtils.java

* feat: 외부 API 호출 툴 Feign 설정
* feat: Apple 로그인 구현 + 회원가입 Reqeust Provider 추가

feat: 애플 로그인 API 구현 (#267)

---

src/main/java/com/shallwe/domain/auth/application/AuthService.java
src/main/java/com/shallwe/domain/auth/dto/AppleSignInReq.java
src/main/java/com/shallwe/domain/auth/dto/SignUpReq.java
src/main/java/com/shallwe/domain/auth/exception/InvalidProviderIdException.java
src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
src/main/java/com/shallwe/domain/user/domain/repository/UserRepository.java

* feat: 외부 API 호출 툴 Feign 설정
* feat: Apple 로그인 구현 + 회원가입 Reqeust Provider 추가
* fix: Claims sub 항목 빼서 쓰게 수정
* fix: AuthorizationCode Request 제거

fix: Claims sub 항목으로 사용하게 수정 (#269)

---

src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoServiceImpl.java
src/main/java/com/shallwe/domain/reservation/application/ReservationCheckServiceImpl.java
src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/dto/request/OwnerReservationCreate.java
src/main/java/com/shallwe/domain/reservation/exception/InvalidReceiverException.java
src/main/java/com/shallwe/domain/reservation/exception/InvalidSenderException.java
src/main/java/com/shallwe/domain/reservation/exception/InvalidUserException.java
src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java

예외 분리, 
조회 관련 ENUM 수정 
Closes #271

예약 예외 분리하고 ENUM로직을 수정한다. 

---

src/main/java/com/shallwe/global/error/ApiControllerAdvice.java
src/main/java/com/shallwe/global/payload/ResponseCustom.java

chore: Error Response 형식 수정

---

src/main/java/com/shallwe/domain/auth/dto/request/NaverCloudSmsReq.java
src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftRepository.java
src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationService.java
src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
src/main/java/com/shallwe/domain/reservation/dto/request/OwnerReservationCreate.java
src/main/java/com/shallwe/domain/reservation/dto/response/ReservationResponse.java
src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
src/main/java/com/shallwe/domain/shopowner/domain/ShopOwner.java
src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java
src/main/java/com/shallwe/global/infrastructure/sms/dto/AlimTalkReq.java
src/main/java/com/shallwe/global/infrastructure/sms/dto/MessageMapping.java

feat: 알림톡 기능 구현 / 예약등록 알림톡 적용

---

.gitignore
src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
src/main/java/com/shallwe/domain/reservation/exception/InvalidReservationUpdateException.java
src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java

예약 수정시 상태 변경
예약 추가 관련 동시성 처리 (비관적 락 사용) 
예약 삭제 관련 로직 수정 
( 유저 예약 취소(BOOKED상태) : BOOKED -> WAITING
유저 예약 확정 후 취소: CONFIRMED -> CANCELLED)
Closes #285

예약 관련 로직을 수정한다. 

---

.gitignore
src/main/java/com/shallwe/domain/auth/dto/request/NaverCloudSmsReq.java
src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftRepository.java
src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationService.java
src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
src/main/java/com/shallwe/domain/reservation/dto/request/OwnerReservationCreate.java
src/main/java/com/shallwe/domain/reservation/dto/request/UpdateReservationReq.java
src/main/java/com/shallwe/domain/reservation/dto/response/ReservationResponse.java
src/main/java/com/shallwe/domain/reservation/exception/InvalidReservationUpdateException.java
src/main/java/com/shallwe/domain/reservation/exception/NotAvailableReservationStatusException.java
src/main/java/com/shallwe/domain/reservation/exception/UserReservationMismatchException.java
src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
src/main/java/com/shallwe/domain/shopowner/domain/ShopOwner.java
src/main/java/com/shallwe/domain/shopowner/exception/NotReservedException.java
src/main/java/com/shallwe/domain/shopowner/exception/ShopOwnerExperienceGiftMismatchException.java
src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java
src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java
src/main/java/com/shallwe/global/infrastructure/sms/dto/AlimTalkReq.java
src/main/java/com/shallwe/global/infrastructure/sms/dto/MessageMapping.java

feat: 알림톡 기능 적용

---

src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java

- JPQL @Param 등록해서 오류 수정
- 템플릿 형식 오류 수정

fix: 예약 등록 알림톡 오류 수정

---

src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java

* feat: 알림톡 기능 구현 / 예약등록 알림톡 적용
* feat: 예약 확정 알림톡 적용
* feat: 예약 확정 + 초대장 알림톡 적용
* feat: 예약 취소 알림톡 구현
* feat: 예약 취소 알림톡 구현
* fix: 예약 확정 로직 수정
* feat: 예약 변경 알림톡 적용
* fix: 예약 등록 알림톡 오류 수정

fix: 예약 등록 알림톡 오류 수정 (#291)

---

src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java

* feat: 알림톡 기능 구현 / 예약등록 알림톡 적용
* feat: 예약 확정 알림톡 적용
* feat: 예약 확정 + 초대장 알림톡 적용
* feat: 예약 취소 알림톡 구현
* feat: 예약 취소 알림톡 구현
* fix: 예약 확정 로직 수정
* feat: 예약 변경 알림톡 적용
* fix: 예약 등록 알림톡 오류 수정
* fix: 예약 등록 알림톡 수신자 sender로 설정

fix: 예약 등록 시 Receiver한테 알림톡 가는 현상 수정 (#293)

---

src/main/java/com/shallwe/domain/reservation/application/ReservationCheckServiceImpl.java
src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java

fix:  예약중인 상태만 조회할 수 있도록 수정
Closes #295 
Closes #294

fix:  사장님은 예약중인 상태만 조회할 수 있도록 수정
